### ISSUE TITLE
Unable to get polymer-cli setup on mac

### ISSUE THREAD

**Issue by vikjung** [Polymer/polymer-cli#220] opened 2016-05-27 14:31 UTC
Get following errorr

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! file /Users/Vikmac/.npm/minimist/1.2.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /Users/Vikmac/.npm/minimist/1.2.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Vikmac/Documents/workspace/shop-app/shop/npm-debug.log

**Comment by justinfagnani** [comment] 2016-05-27 15:06
Interesting that the installation failed inside minimist. Maybe a network error? Can you try again?

What version of node and npm are you running?

**Comment by vikjung** [comment] 2016-05-27 17:00
Tried multiple times same issue.   Node - v4.4.5,  npm - 2.15.5

Happens after -
-----
selenium-standalone installation finished
-----

**Comment by FredKSchott** [comment] 2016-05-27 20:39
I cannot reproduce on my mac, with your versions of node & npm.

@vikjung Can you try running `npm install -g polymer-cli --verbose` and pasting the full output here?

**Comment by vikjung** [comment] 2016-05-27 22:08
Attached detail

[polymer-cli issue.txt](https://github.com/Polymer/polymer-cli/files/287421/polymer-cli.issue.txt)

**Comment by FredKSchott** [comment] 2016-05-27 22:43
It looks like you have a bad package.json in your collection of global npm dependencies (~/.npm). You can run `cat /Users/Vikmac/.npm/minimist/1.2.0/package/package.json` on your machine to confirm that that file is empty (it most certainly shouldn't be).

Since this isn't a polymer-cli problem and is a problem with your environment (or possibly npm) I'm closing this issue. I'd recommend uninstalling/reinstalling that global package via npm and seeing if that fixes it.

Good luck!

**Closed by FredKSchott** 2016-05-27 22:43 UTC
Labels: Priority: Medium, Status: Available, Type: Bug

**Comment by vikjung** [comment] 2016-05-28 06:15
Uninstall and reinstall of node and npm doesnt fix it. I think cached packages from previous bower install were messed up.

Executed ---    npm cache clean
~/.npm is a cache that npm uses to avoid re-downloading the same package multiple times.   That was having 0 byte package.json for different packages like minimist, object-assign and others

this got me further but Still am Not able to run polymer help  --- 

-----
selenium-standalone installation finished
-----
polymer-cli@0.11.0 node_modules/polymer-cli
├── clone@1.0.2
├── vinyl@1.1.1 (clone-stats@0.0.1, replace-ext@0.0.1)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── dom5@1.3.1 (parse5@1.5.1)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── merge-stream@1.0.0 (readable-stream@2.1.4)
├── minimatch-all@1.0.2 (minimatch@1.0.0)
├── css-slam@1.1.0 (shady-css-parser@0.0.7)
├── multipipe@0.3.0 (duplexer2@0.1.4)
├── resolve@1.1.7
├── github@0.2.4 (mime@1.3.4)
├── plylog@0.4.0 (winston@2.2.0)
├── liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, findup-sync@0.3.0)
├── tar-fs@1.13.0 (pump@1.0.1, mkdirp@0.5.1, tar-stream@1.5.2)
├── gulp-if@2.0.1 (gulp-match@1.0.2, ternary-stream@2.0.0)
├── gunzip-maybe@1.3.1 (is-gzip@1.0.0, is-deflate@1.0.0, through2@0.4.2, pumpify@1.3.4, peek-stream@1.1.1, browserify-zlib@0.1.4)
├── fs-extra@0.30.0 (path-is-absolute@1.0.0, graceful-fs@4.1.4, klaw@1.2.0, jsonfile@2.3.1, rimraf@2.5.2)
├── sw-precache@3.2.0 (es6-promise@3.2.1, pretty-bytes@3.0.1, dom-urls@1.1.0, lodash.defaults@4.0.1, lodash.template@4.2.5, mkdirp@0.5.1, glob@6.0.4, sw-toolbox@3.1.1, meow@3.7.0)
├── polyserve@0.12.0 (opn@3.0.3, find-port@1.0.1, send@0.10.1, express@4.13.4)
├── uglify-js@2.6.2 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
├── vinyl-fs@2.4.3 (vali-date@1.0.0, is-valid-glob@0.3.0, object-assign@4.1.0, graceful-fs@4.1.4, lazystream@1.0.0, through2-filter@2.0.0, strip-bom-stream@1.0.0, strip-bom@2.0.0, lodash.isequal@4.2.0, readable-stream@2.1.4, gulp-sourcemaps@1.6.0, mkdirp@0.5.1, duplexify@3.4.3, glob-stream@5.3.2)
├── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── vulcanize@1.14.8 (path-posix@1.0.0, nopt@3.0.6, es6-promise@2.3.0, update-notifier@0.6.3)
├── gulp@3.9.1 (interpret@1.0.1, pretty-hrtime@1.0.2, deprecated@0.0.1, archy@1.0.0, minimist@1.2.0, tildify@1.2.0, semver@4.3.6, v8flags@2.0.11, orchestrator@0.3.7, gulp-util@3.0.7, vinyl-fs@0.3.14)
├── gulp-html-minifier@0.1.8 (event-stream@3.3.2, html-minifier@1.5.0, gulp-util@2.2.20, htmllint@0.2.7)
├── polylint@2.10.1 (path-is-absolute@1.0.0, colors@1.1.2, optimist@0.6.1, es6-set@0.1.4)
├── yeoman-environment@1.6.1 (log-symbols@1.0.2, escape-string-regexp@1.0.5, text-table@0.2.0, untildify@2.1.0, debug@2.2.0, diff@2.2.2, globby@4.1.0, mem-fs@1.1.3, grouped-queue@0.3.2, lodash@4.13.1)
├── yeoman-generator@0.23.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, rimraf@2.5.2, async@1.5.2, text-table@0.2.0, pretty-bytes@3.0.1, user-home@2.0.0, xdg-basedir@2.0.0, dargs@4.1.0, class-extend@0.1.2, debug@2.2.0, istextorbinary@1.0.2, find-up@1.1.2, path-exists@2.1.0, nopt@3.0.6, error@7.0.2, cli-table@0.3.1, run-async@2.2.0, mkdirp@0.5.1, glob@7.0.3, shelljs@0.7.0, mem-fs-editor@2.2.1, cross-spawn@2.2.3, underscore.string@3.3.4, read-pkg-up@1.0.1, github-username@2.1.0, dateformat@1.0.12, yeoman-test@1.4.0, gruntfile-editor@1.2.0, download@4.4.3, yeoman-assert@2.2.1, html-wiring@1.2.0, lodash@4.13.1)
├── inquirer@1.0.2 (ansi-escapes@1.4.0, mute-stream@0.0.6, through@2.3.8, cli-width@2.1.0, strip-ansi@3.0.1, pinkie-promise@2.0.1, figures@1.7.0, run-async@2.2.0, string-width@1.0.1, cli-cursor@1.0.2, rx@4.1.0, lodash@4.13.1)
├── generator-polymer-init@0.0.3 (yosay@1.1.1, yeoman-generator@0.21.2)
├── command-line-commands@0.1.2 (feature-detect-es6@1.3.0, array-back@1.0.3, core-js@2.4.0)
├── hydrolysis@1.23.3 (path-is-absolute@1.0.0, estraverse@3.1.0, doctrine@0.7.2, escodegen@1.8.0, espree@3.1.5, babel-polyfill@6.9.0)
├── command-line-args@2.1.6 (array-back@1.0.3, typical@2.4.2, feature-detect-es6@1.3.0, find-replace@1.0.2, command-line-usage@2.0.5, core-js@2.4.0)
└── web-component-tester@4.2.2 (cleankill@1.0.2, sinon-chai@2.8.0, server-destroy@1.0.1, async@1.5.2, stacky@1.3.1, test-fixture@1.1.1, serve-waterfall@1.1.1, nomnom@1.8.1, glob@5.0.15, send@0.11.1, body-parser@1.15.1, express@4.13.4, findup-sync@0.2.1, wct-sauce@1.8.4, chai@3.5.0, accessibility-developer-tools@2.10.0, update-notifier@0.6.3, sinon@1.17.4, socket.io@1.4.6, mocha@2.5.3, multer@1.1.0, lodash@3.10.1, wd@0.3.12, wct-local@2.0.3)
Vik-macs-MacBook-Pro:tire Vikmac$ polymer -help
-bash: polymer: command not found
