### ISSUE TITLE
"polymer build" doesn't inject ES5 adapter when bundling

### ISSUE THREAD

**Issue by flawyte** [Polymer/polymer-cli#811] opened 2017-06-28 09:03 UTC
### Description
`polymer build` doesn't inject `custom-elements-es5-adapter.js` like expected, as the doc says [here][1] :

`
When you use the Polymer CLI to compile your app, the CLI automatically compiles the correct files and injects custom-elements-es5-adapter.js, a lightweight polyfill that lets compiled ES5 work on browsers that support native custom elements.
`

and [here][2] :

`
The --js-compile flag adds the custom-elements-es5-adapter.js adapter for running ES5 code on browsers that support ES6.
`

[1]: https://www.polymer-project.org/2.0/docs/es6#compile
[2]: https://www.polymer-project.org/2.0/toolbox/build-for-production#compiling

### Versions & Environment

- Polymer CLI: 1.2.0
- node: v7.10.0
- Operating System: Linux Mint 17.3 Rosa

#### Steps to Reproduce

1. Create an `/demo/polymer2.html` file with the following content :

```html
<!doctype html>
<html lang="fr">
  <head>
    <title>polymer2</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

    <script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
    <link rel="import" href="../src/demo/polymer2-app.html">
  </head>

  <body>
    <polymer2-app></polymer2-app>
  </body>
</html>
```

2. Create a `/src/demo/polymer2-app.html` file with the following content :

```html
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="polymer2-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <h1>polymer2-app</h1>
  </template>

  <script>
    class Polymer2App extends Polymer.Element {
      static get is() {
        return 'polymer2-app';
      }
    }

    customElements.define(Polymer2App.is, Polymer2App);
  </script>
</dom-module>
```

3. Create a `polymer.json` file with the following content :

```json
{
  "builds": [{
    "bundle": true,
    "css": {"minify": true},
    "html": {"minify": true},
    "js": {"compile": true, "minify": true}
  }],
  "lint": {
    "rules": [
      "polymer-2"
    ]
  }
}
```

4. Build : `polymer build --entrypoint demo/polymer2.html`

#### Expected Results

1. `polymer build` should inject either a `<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>` or the content of the script directly into the compiled `polymer2.html` file
2. When visiting this compiled file in a ES6-ready browser (e.g. Chrome 58), a header with the content `polymer2-app` should appear

#### Actual Results

1. None of that happens
2. Blank page with the following errors in console : `Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

#### Additional information

If I manually add `<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>` in the index file `/demo/polymer2.html`, the compiled ES5 code works but `polymer serve` displays a blank page with the following error in console for every custom element used : `Uncaught TypeError: Class constructor DomModule cannot be invoked without 'new'`.

**Comment by jsilvermist** [comment] 2017-06-28 13:00
Add a property called `entrypoint` with your test file above builds, I believe this is required to inject the `custom-elements-es5-adapter.js adapter` unless the main file is named `index.html`.

**Comment by flawyte** [comment] 2017-06-30 09:30
@jsilvermist Same result.

**Comment by flawyte** [comment] 2017-06-30 10:23
Found it. It's because `bundle` is true. When not bundling, the adapter gets injected via a script tag at build time and everything works fine. But when bundling, the adapter doesn't get injected in any way.

**Comment by flawyte** [comment] 2017-06-30 10:23
Found it. It's because `bundle` is true. When not bundling, the adapter gets injected via a `<script>` tag at build time and everything works fine. But when bundling, the adapter doesn't get injected in any way.

**Comment by usergenic** [comment] 2017-07-06 03:38
At one level the problem appears to be that the `--entrypoint` is treated as a fragment and processed by the bundler; the `<script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>` line gets inlined by the bundler then the adapter is not added because the transform stream looks for the external script reference to the `webcomponentsjs/webcomponents-loader.js` to decide whether to add the adapter.

As for why the `--entrypoint` is treated as a fragment, it gets complicated and the behavior of the CLI/polymer-build is a little counter-intuitive.  I need to try some more tests and update this with a comprehensive plan to fix, because my initial exploration shows this might be nuanced and have a wider area of effect if I just fix.

**Comment by usergenic** [comment] 2017-07-06 19:36
Closing as duplicate of https://github.com/Polymer/polymer-cli/issues/710 - About to send PR with fix.  Follow other issue.

**Closed by usergenic** 2017-07-06 19:36 UTC
Labels: Priority: High, Type: Bug

**Comment by usergenic** [comment] 2017-07-06 19:42
FWIW, I think polymer cli is still a little weird wrt to what it decides to hand to the bundler and what it doesn't.  I'll make a separate issue to investigate that, but the good news is that the specific problem is resolved by putting the adapter script ahead of the bundler call in https://github.com/Polymer/polymer-cli/pull/817

**Comment by usergenic** [comment] 2017-07-06 22:33
Also, I discovered that all hyphenated options for the build command were being ignored because there was an expected but untested conversion of dasherized forms to camelCase.  That's fixed as part of forthcoming PR https://github.com/Polymer/polymer-cli/pull/817
