### ISSUE TITLE
doesn't build on windows

### ISSUE THREAD

**Issue by ncrawlins** [Polymer/polymer-cli#178] opened 2016-05-20 03:01 UTC
on windows 10.  tried with node 4, 5 and 6.  same issue every time, seem to be duplicating the src path before searching for files.

> info:    No file found for C:\temp\polytest\temp\polytest\index.html

Notice how \temp\polytest is duplicated in the path it's searching.  This is after creating a new directory, running the init for "application" and then running build.  Works fine on linux with same versions of cli, node and bower.

**Comment by justinfagnani** [comment] 2016-05-20 16:28
We've seen reports recently of problems on gitbash. What shell are you using?

**Comment by ncrawlins** [comment] 2016-05-20 16:33
it's the same behavior on git-bash and the windows command prompt.

**Comment by tennosys** [comment] 2016-05-22 07:43
same problem here

**Comment by tennosys** [comment] 2016-05-22 09:44
The problem is here
In windows style path, it allways append again with root directory
`if (filepath) {
      // un-escape HTML escapes
      filepath = decodeURIComponent(filepath);

      // If the file path is not already under root, such as /bower_components/...,
      // prefix it with root
      if (!filepath.startsWith(this.analyzer.root)) {
        filepath = path.join(this.analyzer.root, filepath);
      }

      let file = this.analyzer.files.get(filepath);
      if (file) {
        deferred.resolve(file.contents.toString());
      } else {
        logger.info('No file found for', filepath);
      }
      return true;
    }
    return false;
  }`

**Comment by tennosys** [comment] 2016-05-22 10:51
Fixed with 
polymer-cli/src/build/analyzer.ts
```
transform(
      file: File,
      encoding: string,
      callback: (error?, data?: File) => void
    ): void {

    // store the file for access by the resolver force to convert correct os path via path join
    this.files.set(path.join("",file.path), file);

    // If this is the entrypoint, hold on to the file, so that it's fully
    // analyzed by the time down-stream transforms see it.
    if (this.isFragment(file)) {
      callback(null, null);
    } else {
      callback(null, file);
    }

  }
```

and 

```
 if (filepath) {
      //fix windows path root
      filepath = path.join(path.parse(this.analyzer.root).root,filepath)
      // un-escape HTML escapes
      filepath = decodeURIComponent(filepath);

      // If the file path is not already under root, such as /bower_components/...,
      // prefix it with root
      if (!filepath.startsWith(this.analyzer.root)) {
        filepath = path.join(this.analyzer.root, filepath);
      }

      let file = this.analyzer.files.get(filepath);
      if (file) {
        deferred.resolve(file.contents.toString());
      } else {
        logger.info('No file found for', filepath);
      }
      return true;
    }
```

but got another error because uglify script is not created.

**Comment by tennosys** [comment] 2016-05-22 11:30
Finally i can build it now
same problem with path windows/unix style

just modify
polymer-cli/src/build/uglify-transform.ts

import path
`import * as path from 'path';`

Fixing the js file path
```
_transform(file, encoding, callback) {
        // fixing the file path
        file.path = path.join("",file.path);
        if (file.contents && file.path.endsWith('.js')) {
            try {
                let contents = file.contents.toString();
                contents = uglify.minify(contents, UglifyOptions).code;
                file.contents = new Buffer(contents);
                if(file.path.indexOf("_script_") != -1 ){
                    console.log(file.path);
                }
            }
            catch (err) {
                logger.warn(`Unable to uglify file ${file.path}`);
                logger.debug(err);
            }
        }
        callback(null, file);
    }
```

**Comment by justinfagnani** [comment] 2017-04-10 19:02
We've been testing on Windows for a while via Appveyor. Closing this for now, assuming it's been fixed.

**Closed by justinfagnani** 2017-04-10 19:02 UTC
Labels: Area: Build, Platform: Windows, Priority: Critical, Status: Available, Type: Bug
