### ISSUE TITLE
Polymer CLI isn't showing all installed generators

### ISSUE THREAD

**Issue by oneezy** [Polymer/polymer-cli#473] opened 2016-11-24 02:15 UTC
**OS:** 2.10.1.windows.1
**NODE:** 6.3.0
**NPM:** 3.10.3
**POLYMER CLI:** 0.16.0
**BOWER:** 1.7.9
**YO:** 1.8.5

-----

I've installed 20+ custom generators I found in the wild, but when in my `git bash`, I run the command `polymer init`, it will only show the last 2 generators that were globally installed.

Is this a bug or the expected result?

```
Oneeezy@Oneezy MINGW64 ~/Desktop/_templates
$ polymer init
? Which starter template would you like to use?
  1) element: A blank element template
  2) application: A blank application template
  3) shop: The "Shop" Progressive Web App demo
  4) starter-kit: A starter application template, with navigation and "PRPL pattern" loading
  5) vaadin-elements-app: no description
  6) 2-x-app: no description
(Move up and down to reveal more choices)
  Answer:
```

-----

Here's my globally installed generators

```
Oneeezy@Oneezy MINGW64 ~/Desktop/_templates
$ npm list -g --depth=0
+-- generator-generator@1.2.1
+-- generator-polymer-element@0.4.19
+-- generator-polymer-init-2-x-app@0.0.1
+-- generator-polymer-init-adpc-component@1.0.5
+-- generator-polymer-init-appsngen-web-component@0.0.11
+-- generator-polymer-init-clab-app@0.1.0
+-- generator-polymer-init-clab-element@1.0.0
+-- generator-polymer-init-component-template@1.0.0
+-- generator-polymer-init-component-template-demo@1.0.0
+-- generator-polymer-init-custom-app@1.0.0
+-- generator-polymer-init-custom-build@1.0.2
+-- generator-polymer-init-custom-build-es6@1.0.8
+-- generator-polymer-init-custom-build-gae@1.1.5
+-- generator-polymer-init-element-scaffold@0.1.8
+-- generator-polymer-init-i18n-starter-kit@1.0.0
+-- generator-polymer-init-ibm-application@0.3.1
+-- generator-polymer-init-ibm-element@0.1.3
+-- generator-polymer-init-oc-app@0.2.0
+-- generator-polymer-init-poly-me@0.0.1
+-- generator-polymer-init-qairoe-starter-kit@0.0.3
+-- generator-polymer-init-reach-starter-kit@0.0.9
+-- generator-polymer-init-vaadin-charts-app@0.0.5
+-- generator-polymer-init-vaadin-elements-app@0.1.0
```

![image](https://cloud.githubusercontent.com/assets/7369575/20584674/b905b3de-b1ba-11e6-9058-51dafb3bb35d.png)

It's easy to just write out the template name that your installing like this:

`polymer init custom-build`

But that can be a pain having to track these names down each time.

**Comment by FredKSchott** [comment] 2016-11-29 22:57
hmm, I can't reproduce on my machine. I see all installed generators in the list: 

<img width="856" alt="screen shot 2016-11-29 at 2 55 47 pm" src="https://cloud.githubusercontent.com/assets/622227/20732514/eaf889a6-b643-11e6-9c0b-fb946a06a3cf.png">

Can you install yeoman (`npm install -g yo`) and run it (`yo`)? Do you see all of the generators listed ?

**Comment by oneezy** [comment] 2016-11-30 03:59
One thing I forgot to mention is that I'm using **NVM** (for windows) to switch between versions of Node _(not sure if this has anything to do with it..but wouldn't think so?)_

When running `$ yo` in **Node 6.3.0**, I received a `Error: pkg.name and pkg.version required`

I updated to **Node 7.2.0** and reinstalled all global packages (including yo), along w/ 8 of the `generator-polymer-init-custom-builds` _(that I found in the wild)_, to see if the bug persists, and it did:

-----

**Here's a big screenshot of everything:**

![image](https://cloud.githubusercontent.com/assets/7369575/20739034/292510ee-b67d-11e6-8a46-5f72388ebfad.png)


**Here's the error output:**
```
Oneeezy@Oneezy MINGW64 ~/Desktop
$ yo

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\update-notifier\index.js:24
                throw new Error('pkg.name and pkg.version required');
                ^

Error: pkg.name and pkg.version required
    at new UpdateNotifier (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\update-notifier\index.js:24:9)
    at module.exports (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\update-notifier\index.js:108:23)
    at module.exports.resolveGenerators (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\lib\router.js:74:18)
    at C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\lodash\index.js:2874:23
    at C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\lodash\index.js:3073:15
    at baseForOwn (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\lodash\index.js:2046:14)
    at C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\node_modules\lodash\index.js:3346:13)
    at module.exports.Router.updateAvailableGenerators (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\lib\router.js:83:5)
    at runYo (C:\Users\Oneeezy\AppData\Roaming\nvm\v7.2.0\node_modules\yo\lib\cli.js:158:10)

```

**Comment by FredKSchott** [comment] 2016-12-01 00:59
Hmm, this could be a windows bug 

We're just asking yeoman for all generators it has, and then printing all of them. We don't do anything to this list, so I'm pretty confident this is a yeoman bug. If you can get `yo` running, we would know for sure, and you would have something to bring to the yeoman team.

I'm on a mac, so I'll need some time before I can test this on my windows machine.

**Comment by oneezy** [comment] 2016-12-01 04:14
Ok no worries..I'll do a bit more research and file a bug with yeoman and link back here.

**Comment by FredKSchott** [comment] 2016-12-17 03:57
@oneezy any luck? Closing this as a yeoman bug.

**Closed by FredKSchott** 2016-12-17 03:57 UTC

**Comment by oneezy** [comment] 2016-12-18 17:02
I'm starting to think this might be a problem w/ [MinTTY](https://github.com/mintty/mintty).

When I installed Git, I chose _"MinTTY"_ instead of _"Windows CMD"_, and it seems a lot of the time when trying to debug terminal issues, the answer is to _"use the Windows CMD instead"_.

![image](https://cloud.githubusercontent.com/assets/7369575/21295020/53de48ee-c511-11e6-9576-d3399c7e1552.png)

-----

In my Windows CMD Prompt, even though it still only shows **6 lines**, I'm able to scroll through them w/ the arrow keys and the selection is highlighted (something that's not possible w/ `polymer init` in Mintty). 

![image](https://cloud.githubusercontent.com/assets/7369575/21294988/952d3fc2-c510-11e6-8883-76132010647c.png)


Unrelated to Polymer CLI, but I also had Mintty problems when I was trying to install [semantic-release-cli](https://github.com/semantic-release/cli) and one of it's dependencies, [node-gyp](https://github.com/nodejs/node-gyp). The more I use Mintty the more problems I'm seeing... Think this is the final problem that's pushed me to reinstall and choose Windows CMD...that is until I find a better terminal tool for Windows.
