### ISSUE TITLE
Fix deprecated warnings

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer-cli#64] opened 2016-05-09 22:24 UTC
At `npm install -g polymer-cli`:

<img width="850" alt="screen shot 2016-05-10 at 00 23 26" src="https://cloud.githubusercontent.com/assets/1007051/15129963/7e175644-1645-11e6-9765-63d6d6dc1a32.png">

**Comment by FredKSchott** [comment] 2016-05-10 17:05
Digging through these now. All of these are dependencies of our dependencies so we might not be able to get rid of all of them right away.

**Comment by FredKSchott** [comment] 2016-05-10 17:15
`graceful-fs`: Warning is preemptive and refers only to v7 of Node (unreleased and not yet scheduled). People are slowly upgrading to the newest version. We'll keep an eye on this.
`lodash`: Caused by an older version of vinyl.js, which is needed by gulp. Upgrading is a non-trivial task for them. This is planned to be fixed in their next major version. https://github.com/gulpjs/gulp/issues/1604
`jade`: Mocha cannot update until they lose support for node v0.8. https://github.com/mochajs/mocha/issues/2200

**Comment by abdonrd** [comment] 2016-05-10 20:41
@FredKSchott thanks for the digging!

**Comment by FredKSchott** [comment] 2016-05-10 20:50
np!

**Closed** 2016-05-10 20:50 UTC
