### ISSUE TITLE
Authorization issue with polymer-cli build + firebase deploy

### ISSUE THREAD

**Issue by mshockwave** [Polymer/polymer-cli#290] opened 2016-06-25 12:47 UTC
### Description
After using polymer-cli to build project(which is also generated by the tool) and deploy to firebase, if a user want to use google login, the authorization page would redirect to `index.html` of the app rather than normal google login page.
This issue had been filed in polymerfire repo: [issue46@polymerfire](https://github.com/firebase/polymerfire/issues/46)

More precisely, the login page would redirect to `https://<your-firebase-app-id>.firebaseapp.com/_/auth`. But there seems to be a redirecting or rewriting rule which cause that URL redirect to `index.html` instead of google login window. @mgibas in the polymerfire's issue thread also mentioned that the problem was gone after switching to `gulp` to build.

### Versions & Environment

- Polymer CLI: 0.11.1
- Operating System: Mac OS X 10.11.5

#### Steps to Reproduce
1. Create an app that require user to login with google
2. Build the app by polymer-cli
3. Deploy to Firebase
4. When users first login(with google), the window prompt up is `index.html`

#### Expected Results
Step 4 in the above should prompt up google login window

**Comment by mikael2933** [comment] 2016-07-01 09:01
Can you post your firebase.json? It should be in your projects root directory.

**Comment by mshockwave** [comment] 2016-07-01 09:16
@mikael2933 
Sure:
```
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "build/bundled",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```
I use all of the services(realtime database, storage and hosting).
I didn't modify `firebase.json` since `polymer init`

**Comment by locomuco** [comment] 2016-07-04 16:44
I experience the same issue...

using app-drawer-template with firebase + polymer cli

**Comment by mikael2933** [comment] 2016-07-05 11:36
To me, it doesn't seems like a problem with Google login, more like a problem between polymer routes and firebase routes. Firebase rewrites shouldn't change the URL it self. @locomuco exactly what do you experience, is it the same with the URL changing to "/index.html"?

**Comment by locomuco** [comment] 2016-07-05 11:42
@mikael2933 doesn't work without or with rewrite rules.
Does this answer your question?

**Comment by mikael2933** [comment] 2016-07-05 11:54
What doesn't work? Is it the same problem with the URL changing to "/index.html" instead of loading the proper content?

**Comment by locomuco** [comment] 2016-07-05 12:10
It's the same behaviour without and with applied rewrite rules

**Comment by midesweb** [comment] 2016-07-08 00:37
The problem is with the Service Worker's cache. 
The configuration of the service Worker, generated by the Polymer CLI build process, is in the file "sw-precache-config.js"

In that file you will find:

`navigateFallback: '/index.html'`

this configuration is explained in the GoogleChrome/sw-precache repository https://github.com/GoogleChrome/sw-precache 

> Sets an HTML document to use as a fallback for URLs not found in the cache. 

The solution is to configure "navigateFallbackWhitelist" (Works to limit the effect of navigateFallback)

`  navigateFallbackWhitelist: [
    /^\/home\//, 
    /^\/other\// 
  ]`

**Comment by locomuco** [comment] 2016-07-08 16:40
deployed and verified, since this is not a polymer-cli problem either, I'd vote to close this issue here

**Comment by motss** [comment] 2016-07-21 13:09
This is my config. Feel like submitting a PR to fix this issue. Is there any situation where this path `/__/` is necessary?

```js
module.exports = {
  staticFileGlobs: [
    '/index.html',
    '/manifest.json',
    '/bower_components/webcomponentsjs/webcomponents-lite.min.js'
  ],
  navigateFallback: '/index.html',
  navigateFallbackWhitelist: [ /^\/[^\_]+\// ]
};
```

**Comment by FredKSchott** [comment] 2016-08-01 23:43
Thanks for your help @midesweb @locomuco! Sounds like this can be closed, if anyone is still having trouble building please open a new issue.

**Closed by FredKSchott** 2016-08-01 23:43 UTC

**Comment by bennypowers** [comment] 2016-12-21 18:10
Should this be in the docs? The error messages which result from this problem are vague.
