### ISSUE TITLE
Polymer test never returns, does apparently nothing

### ISSUE THREAD

**Issue by JPMoresmau** [Polymer/polymer-cli#224] opened 2016-05-30 10:39 UTC
I create a sample app via `polymer init`. `Polymer serve` works fine. `Polymer test` seems to be starting node, but then nothing happens (I mean, after half an hour, I have no output). Is it normal? Am I supposed to do something else? I expected the default simple test that exercise the sample app component to run and pass.
I'm on Windows, updated polymer-cli this morning. Not sure what version info or more you'd need.
Same thing with `-l chrome`

**Comment by FredKSchott** [comment] 2016-05-31 22:55
Can you run `polymer test --verbose` and post the output here?

Polymer-cli defers to [web-component-tester](https://github.com/Polymer/web-component-tester) for it's test command, so if there is a bug here it's probably happening within there.

Post your output and I'll take a look on my windows machine tomorrow.

**Comment by JPMoresmau** [comment] 2016-06-01 05:55
I've turned off my anti virus, to be sure. 

```
polymer test --verbose
debug:   got args:
{ args: [ 'test', '--verbose' ] }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command parsed
{ name: 'test',
  command:
   { name: 'test',
     options: { _all: { verbose: true }, global: { verbose: true } } } }
debug:   command options found
{ options: { verbose: true } }
debug:   config read
{ root: 'C:\\Users\\jean-philippem\\Desktop\\Temp\\app1',
  entrypoint: 'C:\\Users\\jean-philippem\\Desktop\\Temp\\app1\\index.html',
  fragments: [],
  inputs: [ 'C:\\Users\\jean-philippem\\Desktop\\Temp\\app1\\index.html' ] }
debug:   Running command...
step: loadPlugins
step: configure
hook: configure
```

Been running for half an hour now... I see a node process running polymer.js, with no processor nor disk activity (did 4914 disk reads, 3 disk writes according to Task Manager).

**Comment by jwuliger** [comment] 2016-06-04 19:37
Just an FYI. `polymer test` (Windows 10 Ent, Node 6.2) took about 5 minutes for it to show it was doing anything. It did work though. IE 11 fails, but hey were are talking about IE here ;). Also worth noting I ran `polymer test` on the shop app. I am still playing with all the new toys!

**Comment by pomber** [comment] 2016-09-12 00:40
Same happening here, running polymer test after polymer init. 
It took more than an hour in `hook: configure` before running the tests.

**Comment by angst7** [comment] 2016-09-26 00:31
FWIW I'm getting the same problem on Windows 10, polymer-cli 0.16.0, and Node 6.3.1.   
Create a new project with polymer init.  Run polymer test --verbose, and it sits at "hook: configure" for about 10 minutes before resuming.  Subsequent runs take just under a minute.

**Comment by FredKSchott** [comment] 2016-09-28 14:51
Hmm, I can't reproduce on my machine but would love to get this fixed.

Can anyone running into this issue install and run https://github.com/Polymer/web-component-tester directly? polymer-cli delegates to WCT for the test command. Finding out if normal WCT is working will be a first step towards finding the bug.

**Comment by angst7** [comment] 2016-09-30 01:43
Installed web-component-tester 4.3.4, and I get the same behavior: wct hangs at `hook: configure` for several minutes before continuing.  I had a look over at the web-component-tester issues and found  Polymer/web-component-tester#287  So it appears this is a wct issue, not a polymer-cli issue.

**Comment by FredKSchott** [comment] 2016-10-03 22:48
That's not good 😞 I'll close this issue for the CLI and try to take a look at Polymer/web-component-tester#287 as soon as I can.

**Closed by FredKSchott** 2016-10-03 22:48 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
