### ISSUE TITLE
polymer-cli global install error

### ISSUE THREAD

**Issue by guss77** [Polymer/polymer-cli#836] opened 2017-08-03 05:38 UTC
### Description

npm error when running `npm install -g polymer-cli` as root. 

This is done in CI process in a Docker container.

### Versions & Environment

- Polymer CLI: 1.3.1
- node: 8.2.1
- npm: 5.3.0
- Operating System: Debian 8

#### Steps to Reproduce

To reproduce, build this Dockerfile:

```
FROM node
RUN npm install -y polymer-cli
```

#### Expected Results

NPM should install polymer-cli without an error.

#### Actual Results

We get an error in the output and the installation exists with error code 1:

```
> wd@1.4.0 install /usr/local/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts

/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/polymer-cli/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm info lifecycle wd@1.4.0~install: Failed to exec install script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.4.0 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-02T04_53_27_270Z-debug.log
```

The log file mentioned in the output says:

```
...
24890 silly install wd@1.4.0
24891 info lifecycle wd@1.4.0~install: wd@1.4.0
24892 verbose lifecycle wd@1.4.0~install: unsafe-perm in lifecycle false
24893 verbose lifecycle wd@1.4.0~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/polymer-cli/node_modules/wd/node_modules/.bin:/usr/local/lib/node_modules/polymer-cli/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
24894 verbose lifecycle wd@1.4.0~install: CWD: /usr/local/lib/node_modules/polymer-cli/node_modules/wd
24895 silly lifecycle wd@1.4.0~install: Args: [ '-c', 'node scripts/build-browser-scripts' ]
24896 silly lifecycle wd@1.4.0~install: Returned: code: 1  signal: null
24897 info lifecycle wd@1.4.0~install: Failed to exec install script
24898 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
24899 verbose stack Error: wd@1.4.0 install: `node scripts/build-browser-scripts`
24899 verbose stack Exit status 1
24899 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
24899 verbose stack     at emitTwo (events.js:125:13)
24899 verbose stack     at EventEmitter.emit (events.js:213:7)
24899 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
24899 verbose stack     at emitTwo (events.js:125:13)
24899 verbose stack     at ChildProcess.emit (events.js:213:7)
24899 verbose stack     at maybeClose (internal/child_process.js:921:16)
24899 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
24900 verbose pkgid wd@1.4.0
24901 verbose cwd /
24902 verbose Linux 4.10.0-29-generic
24903 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "polymer-cli@next"
24904 verbose node v8.2.1
24905 verbose npm  v5.3.0
24906 error code ELIFECYCLE
24907 error errno 1
24908 error wd@1.4.0 install: `node scripts/build-browser-scripts`
24908 error Exit status 1
24909 error Failed at the wd@1.4.0 install script.
24909 error This is probably not a problem with npm. There is likely additional logging output above.
24910 verbose exit [ 1, true ]
```

### Workarounds:

Using `node:6` as the base image, works out fine.

**Comment by jarrodek** [comment] 2017-08-03 23:51
I have the same error on MacOS.

npm -v: 5.3.0
node -v: v8.2.1

Error message:

> npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
> npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
> /usr/local/bin/polymer -> /usr/local/lib/node_modules/polymer-cli/bin/polymer.js
> 
> > wd@1.4.0 install /usr/local/lib/node_modules/polymer-cli/node_modules/wd
> > node scripts/build-browser-scripts
> 
> /usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
>                     throw err0;
>                     ^
> 
> Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/polymer-cli/node_modules/wd/build'
>     at Object.fs.mkdirSync (fs.js:891:18)
>     at sync (/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
>     at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! wd@1.4.0 install: `node scripts/build-browser-scripts`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the wd@1.4.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/pawelpsztyc/.npm/_logs/2017-08-03T23_47_06_896Z-debug.log

**Comment by femiadeyemi** [comment] 2017-08-04 09:18
This issue is also report here https://github.com/Polymer/polymer-cli/issues/832. Can any of the admins check this? Thanks.

**Comment by guss77** [comment] 2017-08-04 12:40
As details in the NPM issue linked above, the problem is a regression in NPM and can be also worked around by setting `--unsafe-perm`

**Comment by jarrodek** [comment] 2017-08-04 16:35
Wired thing. After I posted my comment I wen't back home. Today I was able to install the cli tool globally without this option. Only thing I did is restart... Another Mac issue then?

**Comment by guss77** [comment] 2017-08-04 18:57
A. With or with out sudo?
B. What is your npm version?
C. What does `npm config get prefix` say?

**Comment by TimvdLippe** [comment] 2017-09-19 19:07
Closing per https://github.com/Polymer/polymer-cli/issues/832#issuecomment-320238339 Thanks again @guss77 !

**Closed by TimvdLippe** 2017-09-19 19:07 UTC

**Comment by HaginCodes** [comment] 2017-10-14 19:30
I recently ran into this issue and what I can say that fixes it is to do   `sudo npm install -g polymer-cli --unsafe-perm`

**Comment by mindthetic** [comment] 2018-01-11 22:27
Running `sudo npm install -g polymer-cli --unsafe-perm` also worked for me. 

`node 8.9.4`
`npm 5.6.0`

**Comment by alohaelegant** [comment] 2018-02-03 04:35
Redic, just troubleshooted the same error. Can you guys (any packages makers) please, include a setup and getting started guide that works. How can we move forward if every step needs troubleshooting?

**Comment by twinforces** [comment] 2018-02-23 19:03
+1 Same thing here. Luckily Google found the error message.

**Comment by louismanson** [comment] 2018-04-10 17:40
`sudo npm install -g polymer-cli --unsafe-perm` works fine for me to, Running **npm: 5.6.0** and
**node: 8.11.1**

**Comment by jairbj** [comment] 2018-04-12 22:47
`sudo npm install -g polymer-cli --unsafe-perm` also worked for me. 
npm: 5.6.0
node: 9.10.1

**Comment by ravi-reglobe** [comment] 2018-04-14 20:56
I have the same problem. and I solved by changing [npm's Default Directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory).

this is not the issue with polymer-cli, but of node and npm installation location.

**Comment by SakuraComputing** [comment] 2018-06-05 12:19
sudo npm install -g polymer-cli --unsafe-perm also worked for me.
npm: 5.6.0
node: 8.11.2

**Comment by EndersonPro** [comment] 2018-06-13 21:00
sudo npm install -g polymer-cli --unsafe-perm also worked for me.
npm: 6.1.0
node: 10.4.1

**Comment by bmargula** [comment] 2018-07-06 05:39
Had the same problem installing polymer-cli on a linux hosted agent in VSTS. `--unsafe-perm` worked for me. Thanks for the workaround.

**Comment by SSGavas** [comment] 2018-07-09 06:18
`--unsafe-perm` worked for me. Thanks for the workaround.

**Comment by hack2root** [comment] 2018-07-13 15:32
why I ever need to do --unsafe-perm on My latest Sierra? It it not so smart as it seems or MacOS support is finally dropped for node/npm developers?

**Comment by aaroncadillac** [comment] 2018-07-18 16:31
@hack2root you could use nvm ;) and you have all the permissons on the world to make polymer works

**Comment by a854363956** [comment] 2018-07-29 04:31
sudo npm install -g polymer-cli --unsafe-perm also worked for me.
npm: 6.2.0
node: v8.11.3

**Comment by anneb** [comment] 2018-08-06 14:16
Same error, fixed with:
sudo npm install -g polymer-cli --unsafe-perm
npm: 6.2.0
node: v8.0.0
Ubuntu 16.04.5 LTS

**Comment by andylamax** [comment] 2018-08-08 11:12
--unsafe-perm worked for me too

**Comment by me89** [comment] 2018-10-11 04:35
Why is it closed? This issue is still in Polymer 3... 

The workaround works with --unsafe-perm worked for me as well.
MacOs 10.14
Node 10.8.0
NPM 6.2.0

**Comment by jsilvermist** [comment] 2018-10-11 04:57
Because this isn't a problem with the `polymer-cli`, it's caused by permission problem with your npm setup. You can either manually configure permissions after installing npm, or use something like nvm which will do it automatically.

**Comment by femiadeyemi** [comment] 2018-12-18 17:13
This seem to be the best solution:
https://github.com/Polymer/polymer-cli/issues/828#issuecomment-319842742

**Comment by Atom-Hydra-7** [comment] 2018-12-21 13:55
### The same error I also suffered in Windows 8.1 x86 32-bit.
