### ISSUE TITLE
build error: Promise rejection when including Google Charts Element

### ISSUE THREAD

**Issue by milesje** [Polymer/polymer-cli#335] opened 2016-08-02 18:27 UTC
### Description
This may be an issue with the polymer-cli & polymer-build, but this component is causing an error while building.

### Versions & Environment

- Polymer CLI: 0.13.0
- node: v4.4.5
- Operating System: Mac OS X 10.11.6

#### Steps to Reproduce
1. Create an application project: `polymer init application`
2. Add Google Charts Element
3. Build: `polymer build`
-->

#### Expected Results
clean build

#### Actual Results
error is thrown:
```
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by FredKSchott** [comment] 2016-08-02 19:03
@milesje thanks for reporting! Can you re-run with the `--verbose` flag, and post your output here? This kind of remote script should be ignored during build, and there is a verbose-only log message that will let us know why it isn't.

**Comment by milesje** [comment] 2016-08-03 17:46
```
polymer build --verbose
debug:   got args:
{ args: [ 'build', '--verbose' ] }
debug:   got default config from file:
{ config:
   { entrypoint: 'index.html',
     shell: 'src/my-app.html',
     fragments: [ 'src/my-view1.html', 'src/my-view2.html', 'src/my-view3.html' ] } }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command 'build' found, parsing command args:
{ args: [ '--verbose' ] }
debug:   command options parsed from args:
{ 'sw-precache-config': 'sw-precache-config.js', verbose: true }
debug:   final project configuration generated:
{ root: '/Users/jmiles/code/raptor-gui',
  entrypoint: '/Users/jmiles/code/raptor-gui/index.html',
  shell: '/Users/jmiles/code/raptor-gui/src/my-app.html',
  fragments:
   [ '/Users/jmiles/code/raptor-gui/src/my-view1.html',
     '/Users/jmiles/code/raptor-gui/src/my-view2.html',
     '/Users/jmiles/code/raptor-gui/src/my-view3.html' ],
  inputs:
   [ '/Users/jmiles/code/raptor-gui/index.html',
     '/Users/jmiles/code/raptor-gui/src/my-app.html',
     '/Users/jmiles/code/raptor-gui/src/my-view1.html',
     '/Users/jmiles/code/raptor-gui/src/my-view2.html',
     '/Users/jmiles/code/raptor-gui/src/my-view3.html' ] }
debug:   Running command...
debug:   building with options
{ sources: undefined,
  includeDependencies: undefined,
  swPrecacheConfig: 'sw-precache-config.js',
  insertDependencyLinks: undefined,
  html: {},
  css: {},
  js: {} }
debug:   building via standard build()...
debug:   sourceGlobs:
	/Users/jmiles/code/raptor-gui/index.html
	/Users/jmiles/code/raptor-gui/src/my-app.html
	/Users/jmiles/code/raptor-gui/src/my-view1.html
	/Users/jmiles/code/raptor-gui/src/my-view2.html
	/Users/jmiles/code/raptor-gui/src/my-view3.html
	/Users/jmiles/code/raptor-gui/src/**/*
	/Users/jmiles/code/raptor-gui/bower.json
debug:   root: /Users/jmiles/code/raptor-gui
debug:   shell: /Users/jmiles/code/raptor-gui/src/my-app.html
debug:   entrypoint: /Users/jmiles/code/raptor-gui/index.html
debug:   fragments: /Users/jmiles/code/raptor-gui/index.html
debug:   sources: /Users/jmiles/code/raptor-gui/src/**/*,/Users/jmiles/code/raptor-gui/bower.json
debug:   includeDependencies:
info:    Building application...
debug:   Reading source files...
debug:   sourceGlobs:
	/Users/jmiles/code/raptor-gui/index.html
	/Users/jmiles/code/raptor-gui/src/my-app.html
	/Users/jmiles/code/raptor-gui/src/my-view1.html
	/Users/jmiles/code/raptor-gui/src/my-view2.html
	/Users/jmiles/code/raptor-gui/src/my-view3.html
	/Users/jmiles/code/raptor-gui/src/**/*
	/Users/jmiles/code/raptor-gui/bower.json
debug:   Reading dependencies...
debug:   Service worker config found
{ staticFileGlobs:
   [ '/index.html',
     '/manifest.json',
     '/bower_components/webcomponentsjs/webcomponents-lite.min.js' ],
  navigateFallback: '/index.html' }
debug:   Analyzing build dependencies...
debug:   addFile: /Users/jmiles/code/raptor-gui/index.html
info:    Generating build/unbundled...
info:    Generating build/bundled...
debug:   addFile: /Users/jmiles/code/raptor-gui/src/my-view1.html
debug:   accept: src/my-view1.html
debug:   accept: bower_components/polymer/polymer.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer.html
debug:   accept: bower_components/paper-card/paper-card.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-card/paper-card.html
debug:   accept: bower_components/paper-button/paper-button.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-button/paper-button.html
debug:   accept: bower_components/iron-flex-layout/iron-flex-layout.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-flex-layout/iron-flex-layout.html
debug:   addFile: /Users/jmiles/code/raptor-gui/src/my-view2.html
debug:   accept: src/my-view2.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer.html
debug:   accept: bower_components/google-chart/google-chart.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart.html
debug:   accept: bower_components/polymer/polymer-mini.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer-mini.html
debug:   addFile: /Users/jmiles/code/raptor-gui/src/my-view3.html
debug:   accept: src/my-view3.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-card/paper-card.html
debug:   addFile: /Users/jmiles/code/raptor-gui/src/my-icons.html
debug:   accept: bower_components/iron-image/iron-image.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-image/iron-image.html
debug:   accept: bower_components/paper-material/paper-material.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-material/paper-material.html
debug:   accept: bower_components/paper-styles/default-theme.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-styles/default-theme.html
debug:   addFile: /Users/jmiles/code/raptor-gui/src/raptor-app.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-button/paper-button.html
debug:   accept: bower_components/paper-behaviors/paper-button-behavior.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-behaviors/paper-button-behavior.html
debug:   accept: bower_components/paper-material/paper-material-shared-styles.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-material/paper-material-shared-styles.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower.json
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-flex-layout/iron-flex-layout.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart.html
debug:   accept: bower_components/iron-ajax/iron-request.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-ajax/iron-request.html
debug:   accept: bower_components/promise-polyfill/promise-polyfill-lite.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/promise-polyfill/promise-polyfill-lite.html
debug:   accept: bower_components/google-chart/google-chart-loader.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart-loader.html
debug:   accept: bower_components/google-chart/google-chart.css
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart.css
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer-mini.html
debug:   accept: bower_components/polymer/polymer-micro.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer-micro.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-image/iron-image.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-material/paper-material.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-styles/default-theme.html
debug:   accept: bower_components/paper-styles/shadow.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-styles/shadow.html
debug:   accept: bower_components/paper-styles/color.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-styles/color.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-behaviors/paper-button-behavior.html
debug:   accept: bower_components/iron-behaviors/iron-button-state.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-behaviors/iron-button-state.html
debug:   accept: bower_components/paper-behaviors/paper-ripple-behavior.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-behaviors/paper-ripple-behavior.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-material/paper-material-shared-styles.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-ajax/iron-request.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/promise-polyfill/promise-polyfill-lite.html
debug:   accept: bower_components/promise-polyfill/Promise.js
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/promise-polyfill/Promise.js
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart-loader.html
debug:   accept: bower_components/google-chart/charts-loader.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/google-chart/charts-loader.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/google-chart/google-chart.css
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/polymer/polymer-micro.html
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer-mini.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer-micro.html' }
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-styles/shadow.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-styles/color.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-behaviors/iron-button-state.html
debug:   accept: bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html
debug:   accept: bower_components/iron-behaviors/iron-control-state.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/iron-behaviors/iron-control-state.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-behaviors/paper-ripple-behavior.html
debug:   accept: bower_components/paper-ripple/paper-ripple.html
debug:   new dependency found, pushing into dependency stream... /Users/jmiles/code/raptor-gui/bower_components/paper-ripple/paper-ripple.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/promise-polyfill/Promise.js
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/google-chart/charts-loader.html
debug:   accept: https://www.gstatic.com/charts/loader.js
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
error:   Promise rejection: Error: no resolver found for https://www.gstatic.com/charts/loader.js
error:   Error: no resolver found for https://www.gstatic.com/charts/loader.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/iron-behaviors/iron-control-state.html
debug:   addFile: /Users/jmiles/code/raptor-gui/bower_components/paper-ripple/paper-ripple.html
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer-mini.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/polymer/polymer-micro.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-card/paper-card.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/iron-flex-layout/iron-flex-layout.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/iron-image/iron-image.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-material/paper-material.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-styles/shadow.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-material/paper-material-shared-styles.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-styles/default-theme.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-styles/color.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-button/paper-button.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-behaviors/paper-button-behavior.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/iron-behaviors/iron-button-state.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/iron-behaviors/iron-control-state.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-behaviors/paper-ripple-behavior.html' }
debug:   dependency has already been pushed, ignoring...
{ dep: 'bower_components/paper-ripple/paper-ripple.html' }
```

**Comment by FredKSchott** [comment] 2016-08-03 18:58
@milesje arg you're right, I can still reproduce. Looks to be the ghost of https://github.com/Polymer/polymer-cli/issues/261

Thanks for your help reporting! Since we're tracking this already in #261 I'll go ahead and close this as a duplicate

**Closed by FredKSchott** 2016-08-03 18:58 UTC
