### ISSUE TITLE
Lazy loading dependencies not loaded correctly

### ISSUE THREAD

**Issue by ralcar** [Polymer/polymer-cli#284] opened 2016-06-20 05:12 UTC
Polymer: 0.11.1
Node: 5.5.0
Operating System: Windows 10

How to reproduce:
1) run polymer init and select the app-layout with "app-drawer-template" (prpl pattern loading)
2) bower install the paper button with : bower install --save PolymerElements/paper-button
3) To the src/my-view1.html file, add an import to paper-button

<link rel="import" href="../bower_components/paper-button/paper-button.html">

and the add the button with the raised attribute:

<paper-button raised>Hello</paper-button>

4) polymer serve --open

Expected result:
When my-view1 is lazy loaded with importHref, it also loads it´s dependencie (paper-button) and the button is showed with the raised css, elevating it from the page

Actual result:
The button is flat, no elevation, as if the css is not available to it.

This is not just paper-button, i tried with paper-fab resulting in the same behavior.
Im guessing this is a bug (if it is, and not just my error (or the other guy i found that had the same problem on the slack channel)) in the importHref and not the cli, but was not sure where to file that.

The general feeling is that the dependencies are not loaded fully or in time for the polymer controls to be loaded correctly.

**Comment by naoak** [comment] 2016-06-20 05:39
I believe this is dupe of #249 and the root cause is https://github.com/Polymer/polymer/issues/3705. One of workarounds is manually calling Polymer.updateStyles() after imported.

**Comment by ralcar** [comment] 2016-06-20 06:51
Ah ok, thank you, was unaware of this

**Comment by mario-aleo** [comment] 2016-06-21 04:45
This workaround works even better if you call it on the attached event from the lazyloaded component

**Comment by FredKSchott** [comment] 2016-06-21 22:02
Thank you for opening. this is currently being tracked in the polymer repo issue linked above. I'll leave this open for a little while longer for anyone who runs into the same issue while using the CLI.

**Comment by mercmobily** [comment] 2016-07-18 15:55
I am nearly certain that Polymer 1.6.0 fixes this, and therefore this should be closed.

**Closed** 2016-07-28 21:50 UTC
Labels: Status: Completed, Type: Bug
