### ISSUE TITLE
Bug: build/bundled prefix on service worker

### ISSUE THREAD

**Issue by jeffkevin** [Polymer/polymer-cli#380] opened 2016-08-25 06:48 UTC
### Description
The bundled and unbundled service worker PrecacheConfig have `build/bundled` / `build/unbundled` prefix

### Versions & Environment
- Polymer CLI: 0.16.0
- node: 6.4.0
- Operating System: Windows 10

#### Steps to Reproduce
1. Create an application project: `polymer init custom-build`
2. Build: `gulp`
3. Serve: `polymer serve build/bundled`

#### Expected Results
Service worker will work.

#### Actual Results
Service worker throws a lot of 404, due to the prefix `build/bundled` that was added to the service-worker.js

#### Current Fix
After build edit service-worker.js inside the build directories (@line:32) and remove the prefix there.

From:
```javascript
var PrecacheConfig = [["build/bundled/index.html","e72684107df02cd146c2ece478b52e20"],
["build/bundled/src/my-app.html","708a8fdc577d21529d5b3edffa1f0e46"],
["build/bundled/src/my-view1.html","b5faca894bd7d36cd63a16d72736cf87"],
["build/bundled/src/my-view2.html","e592b7008d376dd87df1013fa9208aca"],
["build/bundled/src/my-view3.html","a149b68afc85efa2a8b17476c809f027"],
["build/bundled/src/my-view404.html","b9a28746f736435f74b42f65b65b4eac"]];
```
To:
```javascript
var PrecacheConfig = [["/index.html","e72684107df02cd146c2ece478b52e20"],
["/src/my-app.html","708a8fdc577d21529d5b3edffa1f0e46"],
["/src/my-view1.html","b5faca894bd7d36cd63a16d72736cf87"],
["/src/my-view2.html","e592b7008d376dd87df1013fa9208aca"],
["/src/my-view3.html","a149b68afc85efa2a8b17476c809f027"],
["/src/my-view404.html","b9a28746f736435f74b42f65b65b4eac"]];
```
same goes to unbundled directory, after changing them the 404 issues are gone.

**Comment by FredKSchott** [comment] 2016-08-29 18:36
Sorry I just tried your repro steps and can't reproduce (everything looked fine). This was fixed in an earlier version of polymer-cli/polymer-build, you may want to try a clean reinstallation of both.

**Comment by jeffkevin** [comment] 2016-08-30 08:21
I tried to install freshly both
- polymer-cli
- generator-polymer-init-custom-build

but the result is the same.
sometimes there are no errors when served because of the cache of the other polymer-kits.
please note that this issue occurs only to the custom-build, the other starter kits build fine.

**Comment by eeid26** [comment] 2016-08-30 11:59
yes, I noticed there is a bug in the custom build script (gulp-tasks/project.js) if you are building on windows.
You can fix it by adding bundledPath.replace('\\', '/') and unbundledPath.replace('\\', '/'),

Here is the full code with the fix

```javascript
// Returns a Promise to generate a service worker for bundled output
function writeBundledServiceWorker() {
  // On windows if we pass the path with back slashes the sw-precache node module is not going
  // to strip the build/bundled or build/unbundled because the path was passed in with back slash.
  return polymer.addServiceWorker({
    project: project,
    buildRoot: bundledPath.replace('\\', '/'),
    swConfig: global.config.swPrecacheConfig,
    serviceWorkerPath: global.config.serviceWorkerPath,
    bundled: true
  });
}

// Returns a Promise to generate a service worker for unbundled output
function writeUnbundledServiceWorker() {
  return polymer.addServiceWorker({
    project: project,
    buildRoot: unbundledPath.replace('\\', '/'),
    swConfig: global.config.swPrecacheConfig,
    serviceWorkerPath: global.config.serviceWorkerPath
  });
}
```

**Comment by jeffkevin** [comment] 2016-08-30 12:52
Thank you for this

**Comment by FredKSchott** [comment] 2016-08-30 20:35
@eeid26 could you create an issue in the https://github.com/PolymerElements/generator-polymer-init-custom-build repo?

/cc @robdodson @abdonrd

**Comment by eeid26** [comment] 2016-08-30 23:00
created
https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/30

**Comment by FredKSchott** [comment] 2016-08-31 17:06
Moved to https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/30

**Closed by FredKSchott** 2016-08-31 17:06 UTC
