### ISSUE TITLE
polytool init && polytool serve && open http://localhost:8080/components/my-app/ not getting what I expect

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-cli#84] opened 2016-05-11 18:19 UTC
Repro:

- init a basic application with polytool init (name it my-app)
- run polytool serve
- navigate to http://localhost:8080/components/my-app/ to see re-usable components

When I navigate to this URL I just see the basic homepage - I would expect to see docs for my components?

**Comment by abdonrd** [comment] 2016-05-11 19:22
I think you don't need to visit this link if you created an application. It is only for alone reusable elements.

**Comment by justinfagnani** [comment] 2016-05-11 19:25
I think this is happening because of the shell serving behavior. `/my-app/` doesn't have an index.html, so the shell is served.

We should exclude `/components/`, `/bower_components/`, and `/node_modules/` from the shell serving behavior.

**Comment by justinfagnani** [comment] 2016-05-13 20:09
Fixed in polyserve, which now doesn't do the shell redirect for `.html` files.

**Closed** 2016-05-13 20:09 UTC
Labels: Status: Blocked, Status: Pending, Type: Bug

**Comment by dtruffaut** [comment] 2016-08-19 12:36
`polymer serve` is ok in the dev directory.

But `polymer serve` in the build directory (ex: build/unbundled) suffers the same issue as described above.

It serves an url like `http://localhost:8080/components/MyProjectNameAsDefinedInBowerDotJson/`

The render works, but the incorrect url triggers an error in the console. Indeed, this page is unexpected by the app. And landing on this url is definitively not the expected behavior.

`polymer serve` in build/unbundled should serve the root "`/`" by default. 
(for example: `http://localhost:8080/`)
