### ISSUE TITLE
latest built : treating online resources as local

### ISSUE THREAD

**Issue by christophe-g** [Polymer/polymer-cli#327] opened 2016-08-01 09:26 UTC
Hi, 

I did a build against latest master.
`font-roboto/Roboto.html` is creating the following issue while building

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic"> 
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700"> 
```

```sh
error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/home/christophe/Programming/Polymer/preignition/bower_components/font-roboto/https:/fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic'
error:   Error: ENOENT: no such file or directory, open '/home/christophe/Programming/Polymer/preignition/bower_components/font-roboto/https:/fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic'
    at Error (native)
```

Cheers,
C.

**Comment by FredKSchott** [comment] 2016-08-01 19:20
Duplicate of #261
See fix in polymer-build library https://github.com/Polymer/polymer-build/pull/16

**Closed by FredKSchott** 2016-08-01 19:20 UTC
