### ISSUE TITLE
[BUG] in update check script

### ISSUE THREAD

**Issue by AliMD** [Polymer/polymer-cli#735] opened 2017-05-14 12:19 UTC
### Description
After install update and check the version i see update available  

![screen shot 2017-05-14 at 4 46 00 pm](https://cloud.githubusercontent.com/assets/697913/26033645/de13975e-38c4-11e7-9ab0-8f0122cbd51e.png)

### Versions & Environment

- Polymer CLI: v0.18.3
- node: v7.7.0
- Operating System: OSX v10.11.6

#### Steps to Reproduce
```bash 
$ polymer --version
0.18.1
...
Update available 0.18.1 → 0.18.3 

$ npm i -g polymer-cli
....

$ polymer --version
0.18.3
...
Update available 0.18.1 → 0.18.3 
```

**Comment by stramel** [comment] 2017-05-20 03:50
Noticing this too...

![image](https://cloud.githubusercontent.com/assets/855184/26272728/9397e0a2-3ce5-11e7-9e2b-b234afccd62f.png)

**Comment by FredKSchott** [comment] 2017-05-23 23:54
Huh... strange. We use a 3rd party package for 100% of this logic, so the bug is probably in there: https://github.com/yeoman/update-notifier

In the past these bugs have been impossible to track down / debug since they only occur once and then never again. I'm going to close this as a won't fix, but if anyone can create a set of steps that are repeatably reproducible then we could potentially reopen and take a look.

Either way, thanks for filing and bringing this up, for anyone searching the issues in the future.

**Closed by FredKSchott** 2017-05-23 23:54 UTC

**Comment by stramel** [comment] 2017-05-24 00:38
Specifically https://github.com/yeoman/update-notifier/issues/67
Will see if I can look into it
