### ISSUE TITLE
Polymer CLI not respecting ctrl+C

### ISSUE THREAD

**Issue by pik** [Polymer/polymer-cli#392] opened 2016-09-02 18:42 UTC
![screenshot from 2016-09-02 13-39-49](https://cloud.githubusercontent.com/assets/10236920/18214530/117d6f86-7113-11e6-899e-2652b6391134.png)

**Comment by FredKSchott** [comment] 2016-09-08 19:02
Duplicate of https://github.com/Polymer/polymer-cli/issues/341.

We've prioritized fixing for this in the next version.

**Closed by FredKSchott** 2016-09-08 19:02 UTC
