### ISSUE TITLE
cli 0.9.0 fails: Cannot find module '..'

### ISSUE THREAD

**Issue by qqiao** [Polymer/polymer-cli#210] opened 2016-05-26 19:43 UTC
node version: 6.2.0
Polymer-cli version: 0.9.0

Error message:

```
$ polymer init
module.js:442
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/bin/polymer.js:19:36
    at /home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/q/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:92:31)
```

**Comment by yordis** [comment] 2016-05-26 19:47
@justinfagnani @FredKSchott Yeah, the 0.9 version introduce this one :(

**Comment by qqiao** [comment] 2016-05-26 19:48
Same on node v4.4.5

**Comment by dannybrian** [comment] 2016-05-26 19:48
Also on 4.4.5. It's not just init, it's polymer cli.

**Comment by benjamincobb** [comment] 2016-05-26 20:09
I also have this problem. Introduced with 0.9.0.

**Comment by justinfagnani** [comment] 2016-05-26 20:11
I'll look at this ASAP

**Comment by taviLaies** [comment] 2016-05-26 20:25
+1

**Comment by thomasweitzel** [comment] 2016-05-26 20:34
After $ npm -g install polymer-cli there's no "lib" directory anymore ...

**Comment by FredKSchott** [comment] 2016-05-26 20:35
This is caused by https://github.com/Polymer/polymer-cli/issues/192

The `depcheck` task called inside of `build-all` is failing, causing the actually build task to never be run.

**Comment by FredKSchott** [comment] 2016-05-26 20:50
Fix submitted here: https://github.com/Polymer/polymer-cli/pull/211

**Comment by FredKSchott** [comment] 2016-05-26 21:47
Proper fix submitted and reviewed here: #212 
We're just waiting for tests to run/pass and then we'll cut a new version, hang tight

**Comment by justinfagnani** [comment] 2016-05-26 22:42
Should be fixed in 0.10.0 now. Sorry for the problems!

**Closed** 2016-05-26 22:42 UTC
Labels: Priority: Critical, Status: Accepted, Type: Bug
