### ISSUE TITLE
Proposal: `polymer test` requires a package-local installation of wct

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-cli#522] opened 2016-12-19 18:42 UTC
Currently the cli includes a copy of wct. What if instead it simply delegated to the version of wct that is installed in the project under test? 

### Advantages:

* More reproducible test results, as the project under test is in control of the version of wct that is used to test their project.
* The `wct` command will also defer to any local installations of the wct package.
* Much faster and lighter weight installs of `polymer-cli`, especially for users who aren't (yet) interested in testing.

### Disadvantages:

* projects/elements will want to add a package.json file if they don't already have one.
  * this is ameliorated by two facts:
    * we plan to move to npm in the long term anyways, so we'll have to do this work at some point
    * most existing projects are testing by calling `wct` directly, which won't be broken by this (though they will soon start seeing a warning that encourages a local install).

**Comment by notwaldorf** [comment] 2016-12-19 18:47
I think I'm generally in favour of this (I defer to @cdata though whose better at using tools than me). Can we make sure to add a non-cryptic message if we try to run it without a local copy of `wct` installed? I know `tattoo` had a problem with this in the past

**Comment by rictic** [comment] 2016-12-19 18:49
Yeah, here's roughly the error message that we'd give:

```
    The web-component-tester node module is not installed as a dependency of
    this project (paper-button).

    We recommend that you run this command to add it:
        npm install --save-dev web-component-tester
    or run:
        yarn add web-component-tester --dev

    Doing so will ensure that your project is in control of the version of wct
    that your project is tested with, insulating you from any future breaking
    changes and making your test runs more reproducible.

    Expected a directory to exist at: ~/paper-button/node_modules/web-component-tester/
```

**Comment by cdata** [comment] 2016-12-19 18:49
What seems to be missing here is a proper separation of external test runner and per-project testing library.

Ideally, `polymer test` should always do the same thing regardless of project dependencies: launch browsers, point them at the test page, and aggregate / report the results. It should not care about what the testing library is. Communication between testing library and test runner should happen over some agreed-upon protocol.

Put another way, I don't know why `polymer test` even exists if it is simply an alias for something I already have installed (not to mention `wct` is easier to type than `polymer test`).

**Comment by rictic** [comment] 2016-12-19 18:56
`polymer test` is just a convenience wrapper around `wct`. As far as I understand it, people wanted a one-stop shop for running all of our tooling commands, and thus the polymer-cli was born!

So in this proposal, all that would happen when you ran `polymer test` is that it would:

1. detect that you have a local install of wct at `./node_modules/web-component-tester` and fail with a friendly error message if not
2. run `./node_modules/.bin/wct` with the args passed to `polymer test`

`polymer test` would then be very lightweight, just the `wct` command with some extra guard rails (we didn't want to require a local install of wct when you run `wct` as we felt like that would be too disruptive if we broke everyone who was doing basically `npm i -g web-component-tester && wct` (e.g. all of our travis configs)).

**Comment by justinfagnani** [comment] 2016-12-19 18:57
@cdata: `polymer test`, like all the other commands exists as a UX provision. If you don't even know about WCT, you won't know to install it, whereas `polymer help` -> `polymer test` is a lit path once you have the polymer CLI installed. Most of the commands in the CLI are wrappers for things that could be installed separately.

The point here is that the current situation is very fragile. Changes to WCT can break a project's test because the project never fixed what version of WCT it depended on. We'd like to fix that, reduce the install size of the CLI, and in the future maybe be open to launching other test frameworks.

The changes you're talking about to WCT would be very nice too. I really would like to separate WCT from Mocha, Chai and most of the libraries it bundles. But this is some pretty serious brain surgery that will take a while to do, while unbundling WCT from the CLI could be done very quickly and fix the other immediate issues.

**Comment by justinfagnani** [comment] 2016-12-19 18:58
@rictic I think `polymer test` should offer to install WCT if it's not already. That would be the best UX, IMO.

**Comment by rictic** [comment] 2016-12-19 18:59
I think saying `run this command:` is a pretty good UX/code complexity tradeoff.

**Comment by cdata** [comment] 2016-12-19 19:04
@justinfagnani Please trust that I understand the problem being discussed. It feels condescending when you restate it.

You asked for my opinion and my opinion stands. I think that the proposed solution excuses us from designing the right thing, and also from performing an austere audit of our Node module dependency tree.

The changes I'm describing actually address the major problem that has been framed here: when the test runner and the testing library are separate, the component author no longer needs to trust that her tests will run in a reproducible fashion as `polymer test` changes over time.

On an editorial note, this seems to be a hypothetical problem that we are trying to solve. I agree that it is a real and likely one, but I'm also in favor of solving hypothetical problems with a good design rather than a hasty one that incurs additional costs (in the form of repo complexity).

**Comment by cdata** [comment] 2016-12-19 19:08
(And by "good design", I do not intend to make a value judgement on the current proposal; I actually mean that this deserves to be designed more formally e.g., in a document not an issue).

**Comment by cdata** [comment] 2016-12-19 19:40
@justinfagnani

> Changes to WCT can break a project's test because the project never fixed what version of WCT it depended on.

This problem seems to be addressed by an existing quality of WCT. Is this correct?
If so, as you imply, a project may fix the version of WCT that it depends on. This is a non-perfect path forward for users who encounter this problem (if such users exist), and no-one is currently blocked.

> reduce the install size of the CLI

We should audit Polymer CLI et al with the strict intention of reducing the scope of the dependency tree. I have been advocating for this for some time now, and I understand that it must seem like an unappealing strategy to solve this given the responses I have received. But, you asked for my opinion and this continues to be where I would start if it were my responsibility to address this.

**Comment by FredKSchott** [comment] 2016-12-19 19:58
+1 on another round of dependency auditing/pruning/cleanup in the CLI, especially once we are done introducing the newest versions of build, serve, etc.

However, we've gone through the dependencies several times now and no matter which way you slice it, wct as it exists today accounts for ~45 seconds of install time and 100MB of dependencies. For context, that's more than half of the total 182M production installation size. 

@cdata You can see more from our original investigation here: https://github.com/Polymer/polymer-cli/issues/364, but the tldr is that our dependency problem cannot be fixed without changing something about how the CLI uses WCT.

**Comment by FredKSchott** [comment] 2016-12-19 20:08
fwiw, I'm not sold on asking our users to maintain a separate package.json just for testing. I do not think that that usability cost outweighs the advantages as described. 

+1 that a design doc would really help here, because I'm unclear what our main goals are. Are they to make the CLI install faster and lighter? Then asking the user to install WCT separately would be a much simpler solution. Or, is our goal to give projects more control over their own environment (starting with their own version of WCT)? In that case, I'm not sure any of our users are even asking for that, and we would be fine waiting until we have a clearer NPM story before introducing a `package.json` and npm as a project testing dependency.

**Comment by rictic** [comment] 2016-12-19 23:31
I discussed with @cdata and @azakus offline for a little while, and reflected a bit too.

Here's what I'm thinking: `wct` needs to be rewritten; either gradually or all at once, almost every line of code will need to be changed. This is because it both has a number of design issues, and no one on the team feels comfortable maintaining it. We might be able to maintain command line compatibility, but we won't be able to maintain plugin compatibility (because the state lives in a giant, impossible to reason about god object), and we won't be able to maintain compatibility with existing test suites (as they may assume that any of a grab bag of random dependencies will already have been loaded). In addition, there's an opportunity to provide a significantly nicer user experience, via persistent browser instances.

Given that this new version of wct wouldn't be at all back compatible, and it would feel nicer to use, we might as well also rebrand it with a new name.

And if we want to do all of that, do we want to push burden down to projects under test to install ~100MB of code in each repo?

**Comment by TimvdLippe** [comment] 2016-12-19 23:41
Nice to see this discussion going and excited for any potential outcome! Since I had opened #519 my current point-of-view as user from the `polymer-cli` as well as `wct` is the following:

Whenever I create an element or application, testing is one of the requirements. As of right now, this mostly consisted of downloading and installing `wct` in some form or another. Most of the time I would resort to downloading the complete `wct` with sauce library, install the webdriver again and have yet another 100MB+ added to my project.

I probably lack a lot of knowledge of the internals of `wct`, but it would be awesome from a user perspective to have `wct` configuration and testing features per project, but the actual test runner (e.g. sauce, browser communication and running the test suits) in only 1 place. That would save every contributor a couple of hundreds of MB for each project, have minimal overhead and would probably be a lot more maintainable too for the tools team.

Once again I probably miss the knowledge of a lot of details so I could have made the wrong assumptions. Just my 2 cents 😄

**Comment by justinfagnani** [comment] 2017-01-13 22:01
I think we're going to shelve this proposal for now and revisit how we coordinate between command lines and test dependencies in https://github.com/Polymer/web-component-tester/issues/477

**Closed by justinfagnani** 2017-01-13 22:01 UTC
