### ISSUE TITLE
Cannot proceed after "polymer init"

### ISSUE THREAD

**Issue by lflee** [Polymer/polymer-cli#187] opened 2016-05-22 07:24 UTC
I try to follow https://www.polymer-project.org/1.0/docs/tools/polymer-cli to create an app project.
But I cannot proceed after `polymer init`. I cannot move to other options by using the Down arrow key. But other init, like `polymer init application` works fine.

I think I has installed the necessary prerequisites - 
![33](https://cloud.githubusercontent.com/assets/3342858/15452861/3f1329ec-2030-11e6-8adf-a8d9e82b1fbc.png)

Is it a bug or I've done something wrong?

**Comment by Inrego** [comment] 2016-05-22 11:12
I have the same issue on Windows. I think it's because they rely on a command called uname, which is not available on Windows.

**Comment by peterblazejewicz** [comment] 2016-05-22 20:45
Folks, there are versions of Node affected by keypress bug:
https://github.com/nodejs/node/issues/5384

**Comment by FredKSchott** [comment] 2016-05-23 18:04
@Inrego @lflee You may have an old version, this was fixed in #171 which was pulled into v0.8.0. Can you reproduce on the newest version on npm?

Please re-open if you can verify this still happening on latest, as that might mean theres still work needed to fix.

**Comment by lflee** [comment] 2016-05-23 19:07
@FredKSchott it doesn't seem working even on v0.8.0. (actually, I was already on v0.8.0 when I raised this issue.)

![screenshot 36](https://cloud.githubusercontent.com/assets/3342858/15481321/766ffea6-215c-11e6-8bac-0e98f1992348.png)

**Comment by FredKSchott** [comment] 2016-05-23 19:35
Thanks for the quick response @lflee 
@azakus can you take a look at this?

**Comment by azakus** [comment] 2016-05-23 20:03
@lflee What version of node do you have?

**Comment by lflee** [comment] 2016-05-23 20:05
@azakus v6.0.0

**Comment by azakus** [comment] 2016-05-23 20:06
Ok, this was fixed in 6.2.0. @justinfagnani we can add a version check, < 4.2.4, 5.0, 5.5-6.1 are busted.

**Comment by lflee** [comment] 2016-05-23 20:12
Thanks @azakus , I installed node v6.2.0 and it's working now.

**Comment by LasaleFamine** [comment] 2016-05-25 21:16
Problem solved also for me upgrading from node v5.7 to v6.2.0.

**Comment by justinfagnani** [comment] 2016-05-26 19:03
We need to add some version checks to the logic for displaying the prompts, so that we're not working around the node bug when it's fixed, and so that we're not failing in 5.x (I thought #171 handled this).

**Comment by jokeyrhyme** [comment] 2016-06-02 20:56
If this is related to https://github.com/nodejs/node/issues/5384 then I have a module that helps identify broken versions of Node:

- https://github.com/jokeyrhyme/is-node-interactive-tty-broken

Do you think it might be worth integrating a similar check into this library? So that a warning or something could be displayed? Or perhaps modifying the "engines" part of package.json to help avoid broken Node versions at installation time?

**Comment by justinfagnani** [comment] 2017-04-10 19:01
We haven't heard reports of this issue in a while, so I assume everyone's moved off the broken version of Node. Closing until we hear of new occurrences.

**Closed by justinfagnani** 2017-04-10 19:01 UTC
Labels: Area: Init, Platform: Windows, Priority: Critical, Status: Available, Type: Bug
