### ISSUE TITLE
Arrow keys don't work

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [Polymer/polymer-cli#94] opened 2016-05-12 12:19 UTC
Hi,

I don't know select application in 'polymer init' command because arrow keys doesn't work.
I'm on Windows and I try PowerShell and CMD terminal.
am I the only one to meet it ?

Thanks.

**Comment by abdonrd** [comment] 2016-05-12 13:33
In OSX is working for me.

**Comment by justinfagnani** [comment] 2016-05-13 19:51
@Geoffrey-Pliez I'm not sure what we can do here since we've completely delegate to yeoman by this point. We don't have any keyboard input handling code at all. Can you verify that this is still an issue?

**Comment by addyosmani** [comment] 2016-05-16 03:26
@Geoffrey-Pliez Could you let us know if you're also experiencing this issue with a typical Yeoman generator? (`npm install -g yo generator-webapp && yo webapp`). We test `yo` pretty heavily on Windows and all the latest releases shouldn't have issues with keyboard navigation at prompt time (we use inquirer for our prompts).

**Comment by Geoffrey-Pliez** [comment] 2016-05-16 07:56
@justinfagnani  @addyosmani  I did a new try and it's still the same.
I know also the issue with yeoman generator.
But I try also on another PC and it's work.
So the Issue is probably due to Windows build 14xxx from Windows insider Program

**Comment by justinfagnani** [comment] 2016-05-17 06:22
Well, I'm going to close this for now. If we get a reproduction that's polymer-cli specific we can re-open.

**Closed by justinfagnani** 2016-05-17 06:22 UTC
Labels: Platform: Windows, Priority: Low, Status: On Hold, Type: Bug
