### ISSUE TITLE
--bundle --js-compile fails

### ISSUE THREAD

**Issue by baocang** [Polymer/polymer-cli#605] opened 2017-03-13 09:00 UTC
### Versions & Environment

- Polymer CLI:0.18.0-pre.13
- node:v7.7.2
- Chrome: Version 56.0.2924.87 (64-bit)
- Operating System: macOS Sierra Version 10.12.3

#### Steps to Reproduce

1. Create an application project: `polymer init polymer-2-application`
2. Build: `polymer build --bundle --js-compile`
3. Serve: `polymer serve build/default`
4. Open In Chrome: [http://127.0.0.1:8081](http://127.0.0.1:8081)
#### Expected Results

The application runs with display `Hello xxx-app`

#### Actual Results

Error is thrown:
`(index):744 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new DomModule ((index):798)
DomModule @ (index):798`
`(index):12198 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at MyApplication.PropertyAccessors ((index):1490)
    at MyApplication.TemplateStamp ((index):2384)
    at MyApplication.PropertyEffects ((index):3673)
    at MyApplication.PolymerElement ((index):5325)
    at new MyApplication ((index):12212)`
![screen shot 2017-03-13 at 4 59 04 pm](https://cloud.githubusercontent.com/assets/16043697/23847667/78627614-080e-11e7-819c-24ddcdba3454.png)

**Comment by FredKSchott** [comment] 2017-03-13 22:37
Can reproduce, but cannot reproduce with each flag separately. I believe this is related to https://github.com/Polymer/polymer-cli/issues/606

**Comment by baocang** [comment] 2017-03-16 03:18
I found the solution that load webcomponents-ce-es5.js before app-shell imported, can polymer-cli do the right thing?

**Comment by FredKSchott** [comment] 2017-03-20 17:06
@baocang I was able to see the same thing too, see my comment in the "Can't use ES5 with v1.0.0-rc.6" issue referenced above for the current investigation. Will most likely be fixed in webcomponentsjs.

**Closed** 2017-03-23 00:29 UTC
