### ISSUE TITLE
 Cannot read property 'previous' of null

### ISSUE THREAD

**Issue by oneezy** [Polymer/polymer-cli#306] opened 2016-07-15 06:12 UTC
## Polymer Shop (build issues)

When running `polymer build --verbose`,

I'm getting a few syntax errors:

```
'SyntaxError: Unexpected character \'#\'',
'SyntaxError: Unexpected character \'`\''
```

**Source Code:** https://github.com/oneezy/shopSFI

**Full output:**
```
Oneeezy@Oneezy MINGW64 ~/Desktop/www_/_clients/diesel/wwwSFI (firebase)
$ polymer build --verbose
debug:   got args:
{ args: [ 'build', '--verbose' ] }
debug:   got default config from file:
{ config:
   { entrypoint: 'index.html',
     shell: 'src/shop-app.html',
     fragments:
      [ 'src/shop-list.html',
        'src/shop-detail.html',
        'src/shop-cart.html',
        'src/shop-checkout.html',
        'src/app-resources.html' ] } }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command 'build' found, parsing command args:
{ args: [ '--verbose' ] }
debug:   command options parsed from args:
{ 'sw-precache-config': 'sw-precache-config.js', verbose: true }
debug:   final project configuration generated:
{ root: 'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI',
  entrypoint: 'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\index.html',
  shell: 'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-app.html',
  fragments:
   [ 'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-list.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-detail.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-cart.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-checkout.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\app-resources.html' ],
  inputs:
   [ 'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\index.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-app.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-list.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-detail.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-cart.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\shop-checkout.html',
     'C:\\Users\\Oneeezy\\Desktop\\www_\\_clients\\diesel\\wwwSFI\\src\\app-resources.html' ] }
debug:   Running command...
debug:   building with options
{ sources: undefined,
  swPrecacheConfig: 'sw-precache-config.js',
  insertDependencyLinks: undefined,
  html: {},
  css: {},
  js: {} }
debug:   building via standard build()...
debug:   shell: C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-app.html
debug:   entrypoint: C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\index.html
debug:   dependencies: C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\**\*
debug:   sources: C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\index.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-app.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-list.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-detail.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-cart.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-checkout.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\app-resources.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\**\*,!build,!build/**/*,!bower_components,!bower_components/**/*,!node_modules,!node_modules/**/*
debug:   fragments: C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-list.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-detail.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-cart.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\shop-checkout.html,C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\src\app-resources.html
debug:   no gulpfile found (searched up from C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI)
info:    Building application...
debug:   Reading source files...
debug:   Reading dependencies...
debug:   Analyzing build dependencies...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Uncaught exception: TypeError: Cannot read property 'previous' of null
error:   TypeError: Cannot read property 'previous' of null
    at Parser.parseDeclarationOrRuleset (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:192:63)
    at Parser.parseRule (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRulelist (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:153:27)
    at Parser.parseDeclarationOrRuleset (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:212:87)
    at Parser.parseRule (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\shady-css-parser\dist\shady-css\parser.js:51:19)
    at css (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\css-slam\index.js:51:39)
    at dom5.queryAll.forEach.styleNode (C:\Users\Oneeezy\AppData\Roaming\nvm\v6.3.0\node_modules\polymer-cli\node_modules\css-slam\index.js:45:36)
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\demo\index.html_script_0.js
debug:
{ message: 'SyntaxError: Unexpected character \'#\'',
  filename: 0,
  line: 2,
  col: 10,
  pos: 11,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_0.js
debug:
{ message: 'SyntaxError: Unexpected character \'#\'',
  filename: 0,
  line: 2,
  col: 8,
  pos: 9,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_1.js
debug:
{ message: 'SyntaxError: Unexpected character \'`\'',
  filename: 0,
  line: 2,
  col: 0,
  pos: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_2.js
debug:
{ message: 'SyntaxError: Unexpected character \'`\'',
  filename: 0,
  line: 2,
  col: 0,
  pos: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_3.js
debug:
{ message: 'SyntaxError: Unexpected character \'`\'',
  filename: 0,
  line: 2,
  col: 0,
  pos: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_4.js
debug:
{ message: 'SyntaxError: Unexpected character \'`\'',
  filename: 0,
  line: 2,
  col: 0,
  pos: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1946:9)\n    at next (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2061:15)\n    at addFile (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:69:33)\n    at C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:75:26)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\web-component-tester\data\index.html_script_0.js
debug:
{ message: 'SyntaxError: Unexpected token: operator (<)',
  filename: 0,
  line: 1,
  col: 6,
  pos: 6,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2103:9)\n    at expr_atom (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2630:9)\n    at maybe_unary (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2792:19)\n    at expr_ops (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2827:24)\n    at maybe_conditional (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2856:20)' }
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\web-component-tester\data\index.html_script_2.js
debug:
{ message: 'SyntaxError: Unexpected token: operator (<)',
  filename: 0,
  line: 2,
  col: 21,
  pos: 22,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1553:11)\n    at croak (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2103:9)\n    at expr_atom (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2630:9)\n    at maybe_unary (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2792:19)\n    at expr_ops (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2827:24)\n    at maybe_conditional (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (C:\\Users\\Oneeezy\\AppData\\Roaming\\nvm\\v6.3.0\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2856:20)' }

```

**Comment by FredKSchott** [comment] 2016-07-27 20:57
Duplicate of #305

**Closed by FredKSchott** 2016-07-27 20:57 UTC
