### ISSUE TITLE
version command broken

### ISSUE THREAD

**Issue by joeblew99** [Polymer/polymer-cli#340] opened 2016-08-04 16:16 UTC
````
x-MacBook-Pro:public apple$ polymer --version
0.13.0
error:   Uncaught exception: TypeError: Cannot read property 'catch' of undefined
error:   TypeError: Cannot read property 'catch' of undefined
    at /Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/bin/polymer.js:32:12
    at /Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:92:31)
    at /Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
x-MacBook-Pro:public apple$ 


````

**Comment by FredKSchott** [comment] 2016-08-04 17:59
Duplicate of #333
Fix here: #334

**Closed by FredKSchott** 2016-08-04 17:59 UTC
