### ISSUE TITLE
polymer test fails on Linux with permission denied error

### ISSUE THREAD

**Issue by doctor-g** [Polymer/polymer-cli#527] opened 2016-12-20 19:24 UTC
### Description

On Linux with bower and polymer-cli installed globally, a permission denied error is thrown when running `polymer test`. This happens during the attempted installation of selenium-standalone, specifically at the creation of directory `/usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium`

Note that the tests run successfully through `wct`, which was also installed globally (as in `npm install -g web-component-tester`).

### Versions & Environment
- Polymer CLI: 0.17.0
- node: 6.9.2
- Operating System: Linux (Mint 18, KDE)

#### Steps to Reproduce
- `npm install -g bower polymer-cli`
- `polymer init --name starter-kit`
- `polymer test`

#### Expected Results
Expected to run the test suite.

#### Actual Results
```
Installing and starting Selenium server for local browsers
----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
to: /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/selenium-server/3.0.1-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
to: /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/chromedriver/2.25-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
to: /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/geckodriver/0.11.1-x64-geckodriver



Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium'

error:   cli runtime exception: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium'
error:   Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium'
    at Error (native)
```

**Comment by rictic** [comment] 2016-12-20 19:26
Does it succeed if you run with `polymer test --skip-selenium-install`?

**Comment by doctor-g** [comment] 2016-12-20 19:34
No, although it produces a different error:
```
Starting Selenium server for local browsers



Error: Missing /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/chromedriver/2.25-x64-chromedriver

error:   cli runtime exception: Error: Missing /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/chromedriver/2.25-x64-chromedriver
error:   Error: Missing /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/.selenium/chromedriver/2.25-x64-chromedriver
    at /usr/lib/node_modules/polymer-cli/node_modules/selenium-standalone/lib/check-paths-existence.js:15:20
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
'''

**Comment by rictic** [comment] 2016-12-20 19:59
Ok, looks like this is a duplicate of https://github.com/Polymer/web-component-tester/issues/235 .

The safe workaround is to use `nvm` rather than a global install of node and npm, that way you have full permissions to write to your node modules directory.

**Closed by rictic** 2016-12-20 19:59 UTC
